//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VodafonNumbers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int ID { get; set; }
        public long Serial { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> ChoosenNo { get; set; }
        public Nullable<int> Package { get; set; }
        public string Mobile1 { get; set; }
        public string Mobile2 { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string CustomerID { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> ActivationDate { get; set; }
        public Nullable<System.DateTime> RejectDate { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
    
        public virtual Number Number { get; set; }
        public virtual Package Package1 { get; set; }
        public virtual Status Status { get; set; }
    }
}
